# Generated by Django 3.1 on 2025-12-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_adtive',
            new_name='is_active',
        ),
    ]
