# Generated by Django 3.1 on 2025-12-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20251216_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_categoty',
            new_name='variation_category',
        ),
    ]
