# Generated by Django 4.2 on 2026-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_productgallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
