# Generated by Django 4.2 on 2026-01-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_country_state_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="country",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
