# Generated by Django 4.2 on 2026-01-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_auto_20251209_1906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
